// demo-snippets/react/SimpleDrawer.tsx
import * as React from 'react';
import { Drawer } from "@nativescript-community/ui-drawer/react";
import { Drawer as NativeScriptDrawer } from "@nativescript-community/ui-drawer";
import { StyleSheet } from "react-nativescript";
import { NSVElement } from "react-nativescript";


export function SimpleDrawer() {
    const drawerRef = React.useRef<NSVElement<NativeScriptDrawer>>(null);

    function onOpenDrawer() {
        drawerRef.current!.nativeView.open("left");
    }

    function onCloseDrawer() {
        drawerRef.current!.nativeView.close("left");
    }

    return (
        <gridLayout>
            <Drawer ref={drawerRef} className="drawer">
                <gridLayout nodeRole="leftDrawer" backgroundColor="white" width="300">
                    <stackLayout row={0}>
                        <stackLayout backgroundColor="#eeeeee" padding="25">
                            <gridLayout columns="80, *" height="100">
                                <stackLayout col={0} style={styles.avatar}>
                                    <label style={styles.avatarLabel}>JS</label>
                                </stackLayout>
                            </gridLayout>
                            <stackLayout>
                                <label fontWeight="bold">John Smith</label>
                                <label>john.smith@example.com</label>
                            </stackLayout>
                        </stackLayout>
                        <stackLayout>
                            <button style={styles.drawerButton} onTap={onCloseDrawer}>My Profile</button>
                            <button style={styles.drawerButton} onTap={onCloseDrawer}>Settings</button>
                            <button style={styles.drawerButton} onTap={onCloseDrawer}>Rate Us</button>
                            <button style={styles.drawerButton} onTap={onCloseDrawer}>Support</button>
                            <button style={styles.drawerButton} onTap={onCloseDrawer}>Contact</button>
                        </stackLayout>
                    </stackLayout>
                </gridLayout>

                <stackLayout nodeRole="mainContent" backgroundColor="white">
                    <button onTap={onOpenDrawer} text="Open Drawer" width="250" marginTop="25" />
                </stackLayout>
            </Drawer>
        </gridLayout>
    );
}

const styles = StyleSheet.create({
    avatar: {
        backgroundColor: "#61DBFB",
        borderRadius: 40,
        height: 80,
        verticalAlignment: "middle"
    },
    avatarLabel: {
        verticanAlignment: "middle",
        horizontalAlignment: "center",
        fontSize: 30,
        color: "white"
    },
    drawerButton: {
        backgroundColor: "transparent",
        margin: 0,
        padding: 0,
        color: "#222222",
        textAlignment: "left",
        paddingLeft: 25,
        height: 50,
        fontSize: 14
    }
});

// demo-snippets/svelte/SimpleDrawer.svelte
<style>
    ActionBar {
        background-color: #b52e31;
        color: white;
    }
    .avatar {
        background-color:#b52e31;
        border-radius: 40;
        height: 80;
        vertical-align: middle;
    }
    .avatar Label {
        vertical-align: middle;
        horizontal-align: center;
        font-size: 30;
        color: white;
    }
    .drawer .button {
        background-color: transparent;
        margin:0;
        padding: 0;
        border-color: #ccc;
        z-index:0;
        border-width: 0 0 0.5 0;
        color: #222222;
        text-align: left;
        padding-left: 25;
        height:50;
        font-size: 14;
    }
    .drawer .button:highlighted { 
        background-color: #eeeeee; 
        color: #222222; 
    }
    Button {
        background-color: #b52e31;
        color: white;
    }
</style>

<page>
    <actionBar title="Simple Drawer">
        <navigationButton text="Go back" />
    </actionBar>
    <stackLayout>

        <drawer bind:this="{drawer}" class="drawer">
            <gridlayout prop:leftDrawer width="300" backgroundColor="white" rows="auto, *">
                <stacklayout row="0">
                    <stacklayout backgroundColor="#eeeeee" padding="25">
                        <gridlayout columns="80, *" height="100">
                            <stacklayout col="0" class="avatar">
                                <label text="JS" />
                            </stacklayout>
                        </gridlayout>
                        <stacklayout>
                            <label text="John Smith" fontWeight="bold" />
                            <label text="john.smith@example.com" />
                        </stacklayout>
                    </stacklayout>
                    <stacklayout>
                        <button text="My Profile" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Settings" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Rate Us" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Support" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Contact" class="button" on:tap="{onCloseDrawer}" />
                    </stacklayout>
                </stacklayout>
            </gridlayout>
        
            <stacklayout prop:mainContent backgroundColor="white">
                <button on:tap="{onOpenDrawer}" text="Open Drawer" width="250" marginTop="25" />
            </stacklayout>
        </drawer>
    </stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
    import { Drawer } from "@nativescript-community/ui-drawer";
    let drawer: Drawer;
    function onOpenDrawer() {
        drawer.open();
    }
    function onCloseDrawer() {
        drawer.close();
    }

</script>
