// demo-snippets/ng/simple-drawer/simple-drawer.component.ts
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import { RouterExtensions } from '@nativescript/angular';
import { Drawer } from "@nativescript-community/ui-drawer";

@Component({
    selector: 'ns-simple-drawer',
    templateUrl: './simple-drawer.component.html',
    styleUrls: ["./simple-drawer.component.css"]
})
export class SimpleDrawerComponent implements OnInit {
    drawer: Drawer;

    @ViewChild("drawer", { static: true }) drawerElementRef: ElementRef;

    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {
        this.drawer = this.drawerElementRef.nativeElement;
    }

    onOpenDrawer() {
        this.drawer.open();
    }

    onCloseDrawer() {
        this.drawer.close();
    }

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Simple Drawer"></Label>
</ActionBar>

<GridLayout>
    <Drawer #drawer class="drawer">
        <GridLayout leftDrawer width="300" backgroundColor="white" rows="auto, *">
            <StackLayout row="0">
                <StackLayout backgroundColor="#eeeeee" padding="25">
                    <GridLayout columns="80, *" height="100">
                        <StackLayout col="0" class="avatar">
                            <Label text="JS"></Label>
                        </StackLayout>
                    </GridLayout>
                    <StackLayout>
                        <Label text="John Smith" fontWeight="bold"></Label>
                        <Label text="john.smith@example.com"></Label>
                    </StackLayout>
                </StackLayout>
                <StackLayout>
                    <Button text="My Profile" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Settings" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Rate Us" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Support" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Contact" class="button" (tap)="onCloseDrawer()"></Button>
                </StackLayout>
            </StackLayout>
        </GridLayout>
    
        <StackLayout mainContent backgroundColor="white">
            <Button (tap)="onOpenDrawer()" text="Open Drawer" width="250" marginTop="25"></Button>
        </StackLayout>
    </Drawer>
</GridLayout>

// demo-snippets/svelte/SimpleDrawer.svelte
<style>
    ActionBar {
        background-color: #b52e31;
        color: white;
    }
    .avatar {
        background-color:#b52e31;
        border-radius: 40;
        height: 80;
        vertical-align: middle;
    }
    .avatar Label {
        vertical-align: middle;
        horizontal-align: center;
        font-size: 30;
        color: white;
    }
    .drawer .button {
        background-color: transparent;
        margin:0;
        padding: 0;
        border-color: #ccc;
        z-index:0;
        border-width: 0 0 0.5 0;
        color: #222222;
        text-align: left;
        padding-left: 25;
        height:50;
        font-size: 14;
    }
    .drawer .button:highlighted { 
        background-color: #eeeeee; 
        color: #222222; 
    }
    Button {
        background-color: #b52e31;
        color: white;
    }
</style>

<page>
    <actionBar title="Simple Drawer">
        <navigationButton text="Go back" />
    </actionBar>
    <stackLayout>

        <drawer bind:this="{drawer}" class="drawer">
            <gridlayout prop:leftDrawer width="300" backgroundColor="white" rows="auto, *">
                <stacklayout row="0">
                    <stacklayout backgroundColor="#eeeeee" padding="25">
                        <gridlayout columns="80, *" height="100">
                            <stacklayout col="0" class="avatar">
                                <label text="JS" />
                            </stacklayout>
                        </gridlayout>
                        <stacklayout>
                            <label text="John Smith" fontWeight="bold" />
                            <label text="john.smith@example.com" />
                        </stacklayout>
                    </stacklayout>
                    <stacklayout>
                        <button text="My Profile" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Settings" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Rate Us" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Support" class="button" on:tap="{onCloseDrawer}" />
                        <button text="Contact" class="button" on:tap="{onCloseDrawer}" />
                    </stacklayout>
                </stacklayout>
            </gridlayout>
        
            <stacklayout prop:mainContent backgroundColor="white">
                <button on:tap="{onOpenDrawer}" text="Open Drawer" width="250" marginTop="25" />
            </stacklayout>
        </drawer>
    </stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
    import { Drawer } from "@nativescript-community/ui-drawer";
    let drawer: Drawer;
    function onOpenDrawer() {
        drawer.open();
    }
    function onCloseDrawer() {
        drawer.close();
    }

</script>
