// demo-snippets/vue/Demo2.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Demo 2" />
        </ActionBar>

        <StackLayout>
            <Label text="This is the second demo..." />
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>

// demo-snippets/ng/demo2/demo2.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';

@Component({
    selector: 'ns-demo2',
    templateUrl: './demo2.component.html'
})
export class Demo2Component implements OnInit {
    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {}

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Demo 2"></Label>
</ActionBar>

<StackLayout>
    <Label text="This is the second demo..."></Label>
</StackLayout>
