// demo-snippets/vue/Development.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Development" />
        </ActionBar>

        <Drawer ref="drawer">
            <GridLayout ~leftDrawer class="drawer" width="300" backgroundColor="white" rows="auto, *">
                <Label text="Left Drawer" />
            </GridLayout>

            <StackLayout ~mainContent backgroundColor="white">
                <Button @tap="onOpenDrawer" text="Open Drawer" width="250" marginTop="25" />
                <CollectionView
                    height="100%"
                    :items="itemList"
                    itemIdGenerator="index"
                    colWidth="50%"
                    rowHeight="200"
                >
                    <v-template>
                        <GridLayout rows="*, auto" :backgroundColor="item.color" class="item">
                            <StackLayout row="1">
                                <Label row="1" :text="item.name" class="title" />
                                <Label row="1" :text="item.color" class="subtitle" />
                            </StackLayout>
                        </GridLayout>
                    </v-template>
                </CollectionView>
            </StackLayout>
        </Drawer>
    </Page>
</template>

<script>
import { ObservableArray } from '@nativescript/core';
export default {
  computed: {
    message() {
      return "Blank {N}-Vue app";
    }
  },
  data() {
      const items = new ObservableArray([
          { index: 0, name: 'TURQUOISE', color: '#1abc9c' },
          { index: 1, name: 'EMERALD', color: '#2ecc71' },
          { index: 2, name: 'PETER RIVER', color: '#3498db' },
          { index: 3, name: 'AMETHYST', color: '#9b59b6' },
          { index: 4, name: 'WET ASPHALT', color: '#34495e' },
          { index: 5, name: 'GREEN SEA', color: '#16a085' },
          { index: 6, name: 'NEPHRITIS', color: '#27ae60' },
          { index: 7, name: 'BELIZE HOLE', color: '#2980b9' },
          { index: 8, name: 'WISTERIA', color: '#8e44ad' },
          { index: 9, name: 'MIDNIGHT BLUE', color: '#2c3e50' },
          { index: 10, name: 'SUN FLOWER', color: '#f1c40f' },
          { index: 11, name: 'CARROT', color: '#e67e22' },
          { index: 12, name: 'ALIZARIN', color: '#e74c3c' },
          { index: 13, name: 'CLOUDS', color: '#ecf0f1' },
          { index: 14, name: 'CONCRETE', color: '#95a5a6' },
          { index: 15, name: 'ORANGE', color: '#f39c12' },
          { index: 16, name: 'PUMPKIN', color: '#d35400' },
          { index: 17, name: 'POMEGRANATE', color: '#c0392b' },
          { index: 18, name: 'SILVER', color: '#bdc3c7' },
          { index: 19, name: 'ASBESTOS', color: '#7f8c8d' }
      ]);
      return {
          itemList: items
      };
  },
  methods: {
      onOpenDrawer() {
          this.$refs["drawer"].open("left");
      }
  }
};
</script>

<style lang="scss" scoped>
.item {
    padding: 10;
    color: white;
    .title {
        font-size: 17;
        font-weight: bold;
    }
    .subtitle {
        font-size: 14;
    }
}
</style>

// demo-snippets/ng/development/development.component.ts
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import { RouterExtensions } from '@nativescript/angular';
import { Drawer } from "@nativescript-community/ui-drawer";

@Component({
    selector: 'ns-development',
    templateUrl: './development.component.html'
})
export class DevelopmentComponent implements OnInit {
    drawer: Drawer;

    items = [
        { index: 0, name: 'TURQUOISE', color: '#1abc9c' },
        { index: 1, name: 'EMERALD', color: '#2ecc71' },
        { index: 2, name: 'PETER RIVER', color: '#3498db' },
        { index: 3, name: 'AMETHYST', color: '#9b59b6' },
        { index: 4, name: 'WET ASPHALT', color: '#34495e' },
        { index: 5, name: 'GREEN SEA', color: '#16a085' },
        { index: 6, name: 'NEPHRITIS', color: '#27ae60' },
        { index: 7, name: 'BELIZE HOLE', color: '#2980b9' },
        { index: 8, name: 'WISTERIA', color: '#8e44ad' },
        { index: 9, name: 'MIDNIGHT BLUE', color: '#2c3e50' },
        { index: 10, name: 'SUN FLOWER', color: '#f1c40f' },
        { index: 11, name: 'CARROT', color: '#e67e22' },
        { index: 12, name: 'ALIZARIN', color: '#e74c3c' },
        { index: 13, name: 'CLOUDS', color: '#ecf0f1' },
        { index: 14, name: 'CONCRETE', color: '#95a5a6' },
        { index: 15, name: 'ORANGE', color: '#f39c12' },
        { index: 16, name: 'PUMPKIN', color: '#d35400' },
        { index: 17, name: 'POMEGRANATE', color: '#c0392b' },
        { index: 18, name: 'SILVER', color: '#bdc3c7' },
        { index: 19, name: 'ASBESTOS', color: '#7f8c8d' }
    ];

    @ViewChild("drawer", { static: true }) drawerElementRef: ElementRef;

    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {
        this.drawer = this.drawerElementRef.nativeElement;
    }

    onOpenDrawer() {
        this.drawer.open();
    }

    onCloseDrawer() {
        this.drawer.close();
    }

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Development"></Label>
</ActionBar>

<StackLayout>
    <Drawer #drawer class="drawer">
        <GridLayout leftDrawer width="300" backgroundColor="white" rows="auto, *">
            <StackLayout>
                <Label text="Left Drawer"></Label>
                <CollectionView 
                    [items]="items"  
                    colWidth="50%" 
                    rowHeight="200"
                >
                    <ng-template let-item="item">
                        <GridLayout rows="*, auto" [backgroundColor]="item.color" class="item">
                            <StackLayout row="1">
                                <Label row="1" [text]="item.name" class="title"></Label>
                                <Label row="1" [text]="item.color" class="subtitle"></Label>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>
                </CollectionView>
            </StackLayout>
        </GridLayout>
    
        <StackLayout mainContent backgroundColor="white" padding="25">
            <Label textWrap="true" text="This development demo contains specific features that are tested in development."></Label>
            <Button (tap)="onOpenDrawer()" text="Open Drawer" width="250" marginTop="25"></Button>
        </StackLayout>
    </Drawer>
</StackLayout>
