// demo-snippets/ng/all-sides/all-sides.component.ts
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import { RouterExtensions } from '@nativescript/angular';
import { Drawer } from "@nativescript-community/ui-drawer";

@Component({
    selector: 'ns-all-sides',
    templateUrl: './all-sides.component.html',
    styleUrls: ["./all-sides.component.scss"],
})
export class AllSidesComponent implements OnInit {
    drawer: Drawer;

    @ViewChild("drawer", { static: true }) drawerElementRef: ElementRef;

    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {
        this.drawer = this.drawerElementRef.nativeElement;
    }

    onOpenDrawer(side: string) {
        if (side === "left")
            this.drawer.open('left');
        else if (side === "right")
            this.drawer.open('right');
        else if (side === "top")
            this.drawer.open('top');
        else if (side === "bottom")
            this.drawer.open('bottom');
    }

    onCloseDrawer() {
        this.drawer.close();
    }

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="All Sides"></Label>
</ActionBar>

<StackLayout>
    <Drawer #drawer class="drawer">
        <GridLayout leftDrawer width="65%" backgroundColor="white" rows="auto, *" padding="25">
            <Label text="Left drawer"></Label>
        </GridLayout>

        <GridLayout rightDrawer width="65%" backgroundColor="white" rows="auto, *" padding="25">
            <Label text="Right drawer"></Label>
        </GridLayout>
    
        <GridLayout topDrawer height="65%" backgroundColor="white" rows="auto, *" padding="25">
            <Label text="Top drawer"></Label>
        </GridLayout>

        <GridLayout bottomDrawer height="65%" backgroundColor="white" rows="auto, *" padding="25">
            <Label text="Bottom drawer"></Label>
        </GridLayout>

        <StackLayout mainContent backgroundColor="white">
            <Button (tap)="onOpenDrawer('left')" text="Open Left Drawer" width="250" marginTop="25"></Button>
            <Button (tap)="onOpenDrawer('right')" text="Open Right Drawer" width="250" marginTop="25"></Button>
            <Button (tap)="onOpenDrawer('bottom')" text="Open Bottom Drawer" width="250" marginTop="25"></Button>
            <Button (tap)="onOpenDrawer('top')" text="Open Top Drawer" width="250" marginTop="25"></Button>
        </StackLayout>
    </Drawer>
</StackLayout>

// demo-snippets/vue3/AllSides.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" @tap="$navigateBack" />
            <Label text="All Sides" />
        </ActionBar>

        <Drawer ref="drawer">
            <GridLayout ~leftDrawer class="drawer" width="65%" height="100%" backgroundColor="white" padding="25">
                <Label text="Left Drawer" verticalAlignment="top" />
            </GridLayout>

            <GridLayout ~rightDrawer class="drawer" width="65%" height="100%" backgroundColor="white" padding="25">
                <Label text="Right Drawer" verticalAlignment="top" />
            </GridLayout>

            <GridLayout ~topDrawer class="drawer" height="65%" width="100%" backgroundColor="white" padding="25">
                <Label text="Top Drawer" verticalAlignment="top" />
            </GridLayout>

            <GridLayout ~bottomDrawer class="drawer" height="65%" width="100%" backgroundColor="white" padding="25">
                <Label text="Bottom Drawer" verticalAlignment="top" />
            </GridLayout>

            <StackLayout ~mainContent backgroundColor="white">
                <Button @tap="onOpenDrawer('left')" text="Open Left Drawer" width="250" marginTop="25" />
                <Button @tap="onOpenDrawer('right')" text="Open Right Drawer" width="250" marginTop="25" />
                <Button @tap="onOpenDrawer('top')" text="Open Top Drawer" width="250" marginTop="25" />
                <Button @tap="onOpenDrawer('bottom')" text="Open Bottom Drawer" width="250" marginTop="25" />
            </StackLayout>
        </Drawer>
    </Page>
</template>

<script setup lang="ts">
import { ref, $navigateBack } from "nativescript-vue"

const drawer = ref(null);

function onOpenDrawer(side: string) {
    drawer.open(side);
}

</script>

<style lang="scss" scoped>
</style>
