// demo-snippets/react/AllSides.tsx
import * as React from 'react';
import { Drawer } from "@nativescript-community/ui-drawer/react";
import { Drawer as NativeScriptDrawer } from "@nativescript-community/ui-drawer";
import { NSVElement } from "react-nativescript";

export function AllSides() {
    const drawerRef = React.useRef<NSVElement<NativeScriptDrawer>>(null);

    function onOpenDrawer(side) {
        drawerRef.current!.nativeView.open(side);
    }

    return (
        <gridLayout>
            <Drawer ref={drawerRef} className="drawer">
                <gridLayout nodeRole="leftDrawer" backgroundColor="white" width="65%" padding="25">
                    <label verticalAlignment="top">Left Drawer</label>
                </gridLayout>

                <gridLayout nodeRole="rightDrawer" backgroundColor="white" width="65%" padding="25">
                    <label verticalAlignment="top">Right Drawer</label>
                </gridLayout>

                <gridLayout nodeRole="topDrawer" backgroundColor="white" height="65%" padding="25">
                    <label verticalAlignment="top">Top Drawer</label>
                </gridLayout>

                <gridLayout nodeRole="bottomDrawer" backgroundColor="white" height="65%" padding="25">
                    <label verticalAlignment="top">Bottom Drawer</label>
                </gridLayout>

                <stackLayout nodeRole="mainContent" backgroundColor="white">
                    <button onTap={() => onOpenDrawer('left')} text="Open Left Drawer" width="250" marginTop="25" />
                    <button onTap={() => onOpenDrawer('right')} text="Open Right Drawer" width="250" marginTop="25" />
                    <button onTap={() => onOpenDrawer('top')} text="Open Top Drawer" width="250" marginTop="25" />
                    <button onTap={() => onOpenDrawer('bottom')} text="Open Bottom Drawer" width="250" marginTop="25" />
                </stackLayout>
            </Drawer>
        </gridLayout>
    );
}

// demo-snippets/vue3/AllSides.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" @tap="$navigateBack" />
            <Label text="All Sides" />
        </ActionBar>

        <Drawer ref="drawer">
            <GridLayout ~leftDrawer class="drawer" width="65%" height="100%" backgroundColor="white" padding="25">
                <Label text="Left Drawer" verticalAlignment="top" />
            </GridLayout>

            <GridLayout ~rightDrawer class="drawer" width="65%" height="100%" backgroundColor="white" padding="25">
                <Label text="Right Drawer" verticalAlignment="top" />
            </GridLayout>

            <GridLayout ~topDrawer class="drawer" height="65%" width="100%" backgroundColor="white" padding="25">
                <Label text="Top Drawer" verticalAlignment="top" />
            </GridLayout>

            <GridLayout ~bottomDrawer class="drawer" height="65%" width="100%" backgroundColor="white" padding="25">
                <Label text="Bottom Drawer" verticalAlignment="top" />
            </GridLayout>

            <StackLayout ~mainContent backgroundColor="white">
                <Button @tap="onOpenDrawer('left')" text="Open Left Drawer" width="250" marginTop="25" />
                <Button @tap="onOpenDrawer('right')" text="Open Right Drawer" width="250" marginTop="25" />
                <Button @tap="onOpenDrawer('top')" text="Open Top Drawer" width="250" marginTop="25" />
                <Button @tap="onOpenDrawer('bottom')" text="Open Bottom Drawer" width="250" marginTop="25" />
            </StackLayout>
        </Drawer>
    </Page>
</template>

<script setup lang="ts">
import { ref, $navigateBack } from "nativescript-vue"

const drawer = ref(null);

function onOpenDrawer(side: string) {
    drawer.open(side);
}

</script>

<style lang="scss" scoped>
</style>
