// demo-snippets/react/Demo1.tsx
import * as React from 'react';
import { Drawer } from "@nativescript-community/ui-drawer/react";
import { Drawer as NativeScriptDrawer } from "@nativescript-community/ui-drawer";
import { NSVElement } from "react-nativescript";


export function Demo1() {
    const drawerRef = React.useRef<NSVElement<NativeScriptDrawer>>(null);

    function onOpenDrawer() {
        drawerRef.current!.nativeView.open("left");
    }

    function onCloseDrawer() {
        drawerRef.current!.nativeView.close("left");
    }

    return (
        <gridLayout>
            <Drawer ref={drawerRef} className="drawer">
                <gridLayout nodeRole="leftDrawer" backgroundColor="white" width="300">
                    <stackLayout row={0}>
                        <stackLayout backgroundColor="#eeeeee" padding="25">
                            <gridLayout columns="80, *" height="100">
                                <stackLayout col={0} className="avatar">
                                    <label>JS</label>
                                </stackLayout>
                            </gridLayout>
                            <stackLayout>
                                <label fontWeight="bold">John Smith</label>
                                <label>john.smith@example.com</label>
                            </stackLayout>
                        </stackLayout>
                        <stackLayout>
                            <button className="button" onTap={onCloseDrawer}>My Profile</button>
                            <button className="button" onTap={onCloseDrawer}>Settings</button>
                            <button className="button" onTap={onCloseDrawer}>Rate Us</button>
                            <button className="button" onTap={onCloseDrawer}>Support</button>
                            <button className="button" onTap={onCloseDrawer}>Contact</button>
                        </stackLayout>
                    </stackLayout>
                </gridLayout>

                <stackLayout nodeRole="mainContent" backgroundColor="white">
                    <button onTap={onOpenDrawer} text="Open Drawer" width="250" marginTop="25" />
                </stackLayout>
            </Drawer>
        </gridLayout>
    );
}

// demo-snippets/ng/demo1/demo1.component.ts
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import { RouterExtensions } from '@nativescript/angular';

import { Drawer } from "@nativescript-community/ui-drawer";
@Component({
    selector: 'ns-demo1',
    templateUrl: './demo1.component.html',
    styleUrls: ["./demo1.component.css"]
})
export class Demo1Component implements OnInit {
    drawer: Drawer;

    @ViewChild("drawer", { static: true }) drawerElementRef: ElementRef;

    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {
        this.drawer = this.drawerElementRef.nativeElement;
    }

    onOpenDrawer() {
        this.drawer.open();
    }

    onCloseDrawer() {
        this.drawer.close();
    }

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Demo 1"></Label>
</ActionBar>

<GridLayout>
    <Drawer #drawer class="drawer">
        <GridLayout leftDrawer width="300" backgroundColor="white" rows="auto, *">
            <StackLayout row="0">
                <StackLayout backgroundColor="#eeeeee" padding="25">
                    <GridLayout columns="80, *" height="100">
                        <StackLayout col="0" class="avatar">
                            <Label text="JS"></Label>
                        </StackLayout>
                    </GridLayout>
                    <StackLayout>
                        <Label text="John Smith" fontWeight="bold"></Label>
                        <Label text="john.smith@example.com"></Label>
                    </StackLayout>
                </StackLayout>
                <StackLayout>
                    <Button text="My Profile" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Settings" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Rate Us" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Support" class="button" (tap)="onCloseDrawer()"></Button>
                    <Button text="Contact" class="button" (tap)="onCloseDrawer()"></Button>
                </StackLayout>
            </StackLayout>
        </GridLayout>
    
        <StackLayout mainContent backgroundColor="white">
            <Button (tap)="onOpenDrawer()" text="Open Drawer" width="250" marginTop="25"></Button>
        </StackLayout>
    </Drawer>
</GridLayout>
